version: '3.8'

services:
  sql-server:
    container_name: cloud_native_sql_server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=yourStrong(!)Password
    ports:
      - "1433:1433"
    volumes:
      - sql-server-data:/var/opt/mssql/data

volumes:
  sql-server-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: 'D:\SQLServerExpressContainerFiles'