CREATE TABLE Authors
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(255) NOT NULL,
	IsDeleted BIT NOT NULL DEFAULT 0
)

CREATE TABLE Books
(
	Id INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Title VARCHAR(255) NOT NULL,
	AuthorId INT NOT NULL,
	IsDeleted BIT NOT NULL DEFAULT 0,
	CONSTRAINT FK_Author FOREIGN KEY (AuthorId) REFERENCES Authors(Id)
)